sudo: true
language: scala
scala: 2.12.6

before_install:
  - wget https://github.com/sormuras/bach/raw/master/install-jdk.sh

matrix:
  include:
    - env: JDK='OpenJDK 10'
      install: . ./install-jdk.sh -F 10 -L GPL

script: sbt 'testOnly IteratorTest'
